import {Variable, Priority, VarList, Mutations, Util, Readable, Schedulable, Writable, Named, Reaction, Deadline, Action, Startup, Scheduler, Timer, Reactor, Port, OutPort, InPort, App } from "./reactor";
import {TimeUnit,TimeInterval, UnitBasedTimeInterval, TimeInstant, Origin, getCurrentPhysicalTime } from "./time"
// Code generated by the Lingua Franca compiler for reactor Source in Composition
// =============== START reactor class Source
class Source extends Reactor {
    t: Timer;
    period: TimeInterval; // Parameter
    count: number; // State
    y: OutPort<number>;
    constructor(period: TimeInterval, parent:Reactor) {
        super(parent);
        this.t = new Timer(this, new UnitBasedTimeInterval(1, TimeUnit.sec), period);
        this.period = period; // Parameter
        this.count = 0; // State
        this.y = new OutPort<number>(this);
        this.addReaction(new class<T> extends Reaction<T> {
            //@ts-ignore
            react(y: Writable<number>, ) {
                var self = this.parent as Source;
                self.count++;
                y.set(self.count);
            }
        }(this, this.check(this.t, ), this.check(this.getWritable(this.y),)));
    }
}
// =============== END reactor class Source

// Code generated by the Lingua Franca compiler for reactor Test in Composition
// =============== START reactor class Test
class Test extends Reactor {
    count: number; // State
    x: InPort<number>;
    constructor(parent:Reactor) {
        super(parent);
        this.count = 0; // State
        this.x = new InPort<number>(this);
        this.addReaction(new class<T> extends Reaction<T> {
            //@ts-ignore
            react(x: Readable<number>, ) {
                var self = this.parent as Test;
                self.count++;
                console.log("Received " + x.get());
                if (x.get() != self.count) { 
                    console.log("FAILURE: Expected " + self.count);
                    self.util.failure();
                    //throw new Error("FAILURE: Expected " + (this.state as any).count);
                }
            }
        }(this, this.check(this.x, ), this.check(this.x, )));
    }
}
// =============== END reactor class Test

// Code generated by the Lingua Franca compiler for reactor Composition in Composition
// =============== START reactor class Composition
class Composition extends App {
    s: Source
    d: Test
    constructor(name: string, timeout: TimeInterval | null, success?: ()=> void, fail?: ()=>void) {
        super(timeout, success, fail);
        this.s = new Source(new UnitBasedTimeInterval(2, TimeUnit.sec), this)
        this.d = new Test(this)
        this._connect(this.s.y, this.d.x);
    }
}
// =============== END reactor class Composition

// ************* Instance Composition of class Composition
let _app = new Composition('Composition', new UnitBasedTimeInterval(5, TimeUnit.sec))
// ************* Starting Runtime for Composition of class Composition
_app._start();
