import {Variable, Priority, VarList, Mutations, Util, Readable, Schedulable, Writable, Named, Reaction, Deadline, Action, Startup, Scheduler, Timer, Reactor, Port, OutPort, InPort, App } from "./reactor";
import {TimeUnit,TimeInterval, UnitBasedTimeInterval, TimeInstant, Origin, getCurrentPhysicalTime } from "./time"
// Code generated by the Lingua Franca compiler for reactor ImportedAgain in Import
// =============== START reactor class ImportedAgain
class ImportedAgain extends Reactor {
    x: InPort<number>;
    constructor(parent:Reactor) {
        super(parent);
        this.x = new InPort<number>(this);
        this.addReaction(new class<T> extends Reaction<T> {
            //@ts-ignore
            react(x: Readable<number>, ) {
                var self = this.parent as ImportedAgain;
                console.log("Received: " + x.get());
                if ((x.get() as number) != 42) {
                    console.log("ERROR: Expected input to be 42. Got: " + x.get())
                    self.util.failure();
                    //throw new Error("ERROR: Expected input to be 42. Got: " + (this.state as any).x.get());
                }
            }
        }(this, this.check(this.x, ), this.check(this.x, )));
    }
}
// =============== END reactor class ImportedAgain

// Code generated by the Lingua Franca compiler for reactor Imported in Import
// =============== START reactor class Imported
class Imported extends Reactor {
    a: ImportedAgain
    x: InPort<number>;
    constructor(parent:Reactor) {
        super(parent);
        this.a = new ImportedAgain(this)
        this.x = new InPort<number>(this);
        this.addReaction(new class<T> extends Reaction<T> {
            //@ts-ignore
            react(x: Readable<number>, a: { x: Writable,  }, ) {
                var self = this.parent as Imported;
                a.x.set(x.get());
            }
        }(this, this.check(this.x, ), this.check(this.x, { x: this.getWritable(this.a.x),  }, )));
    }
}
// =============== END reactor class Imported

// Code generated by the Lingua Franca compiler for reactor Import in Import
// =============== START reactor class Import
class Import extends App {
    a: Imported
    t: Timer;
    constructor(name: string, timeout: TimeInterval | null, success?: ()=> void, fail?: ()=>void) {
        super(timeout, success, fail);
        this.a = new Imported(this)
        this.t = new Timer(this, 0, 0);
        this.addReaction(new class<T> extends Reaction<T> {
            //@ts-ignore
            react(a: { x: Writable,  }, ) {
                var self = this.parent as Import;
                a.x.set(42);
            }
        }(this, this.check(this.t, ), this.check({ x: this.getWritable(this.a.x),  }, )));
    }
}
// =============== END reactor class Import

// ************* Instance Import of class Import
let _app = new Import('Import', new UnitBasedTimeInterval(2, TimeUnit.sec))
// ************* Starting Runtime for Import of class Import
_app._start();
