import {Args, Present, Parameter, State, Variable, Priority, Mutation, Util, Readable, Schedulable, Triggers, Writable, Named, Reaction, Action, Startup, Scheduler, Timer, Reactor, Port, OutPort, InPort, App } from "./reactor";
import {TimeUnit,TimeInterval, UnitBasedTimeInterval, TimeInstant, Origin, getCurrentPhysicalTime } from "./time"
// Code generated by the Lingua Franca compiler for reactor Minimal in Minimal
// =============== START reactor class Minimal
export class Minimal extends App {
    t: Timer;
    constructor (name: string, timeout: TimeInterval | undefined = undefined, keepAlive: boolean = false, success?: () => void, fail?: () => void) {
        super(timeout, keepAlive, success, fail);
        this.t = new Timer(this, 0, 0);
        this.addReaction(
            new Triggers(this.t),
            new Args(this.t),
            function (this, t: Readable<TimeInstant>) {
                console.log("Hello World.");
            }
        );
    }
}
// =============== END reactor class Minimal

// ************* Instance Minimal of class Minimal
let _app = new Minimal('Minimal')
// ************* Starting Runtime for Minimal of class Minimal
_app._start();
