import {Variable, Priority, VarList, Mutations, Util, Readable, Schedulable, Writable, Named, Reaction, Deadline, Action, Startup, Scheduler, Timer, Reactor, Port, OutPort, InPort, App } from "./reactor";
import {TimeUnit,TimeInterval, UnitBasedTimeInterval, TimeInstant, Origin, getCurrentPhysicalTime } from "./time"
// Code generated by the Lingua Franca compiler for reactor Printer in SendingInside2
// =============== START reactor class Printer
class Printer extends Reactor {
    x: InPort<number>;
    constructor(parent:Reactor) {
        super(parent);
        this.x = new InPort<number>(this);
        this.addReaction(new class<T> extends Reaction<T> {
            //@ts-ignore
            react(x: Readable<number>, ) {
                var self = this.parent as Printer;
                console.log("Inside reactor received:" + x.get() );
            }
        }(this, this.check(this.x, ), this.check(this.x, )));
    }
}
// =============== END reactor class Printer

// Code generated by the Lingua Franca compiler for reactor SendingInside2 in SendingInside2
// =============== START reactor class SendingInside2
class SendingInside2 extends App {
    p: Printer
    t: Timer;
    constructor(name: string, timeout: TimeInterval | null, success?: ()=> void, fail?: ()=>void) {
        super(timeout, success, fail);
        this.p = new Printer(this)
        this.t = new Timer(this, 0, 0);
        this.addReaction(new class<T> extends Reaction<T> {
            //@ts-ignore
            react(p: { x: Writable,  }, ) {
                var self = this.parent as SendingInside2;
                p.x.set(1);
            }
        }(this, this.check(this.t, ), this.check({ x: this.getWritable(this.p.x),  }, )));
    }
}
// =============== END reactor class SendingInside2

// ************* Instance SendingInside2 of class SendingInside2
let _app = new SendingInside2('SendingInside2', null)
// ************* Starting Runtime for SendingInside2 of class SendingInside2
_app._start();
