# A grammar file to be used with Canopy:
# https://www.npmjs.com/package/canopy
#
# Explanation and syntax reference: http://canopy.jcoglan.com/
#
# To build:
# `npm install -g canopy`
# `canopy lf.peg --lang javascript` (or java | python | ruby)
grammar LinguaFranca
  Grammar <- Spacing Stament+

  Stament <- Declaration ";" Spacing /  EmbeddedStatement Spacing 
  
  EmbeddedStatement <- "{=" ( !"=" . / "=" !"}" .)* "=}"
  #EmbeddedStatement <- "{=" ([a-zA-Z0-9] / [\s] / ";" / '(' / ')' / ',' )* "=}"
  
  Declaration <- Target / Reactor / Reaction / Clock / Constructor / Composite / Port / InOutParamTrig  # is this right?

  Target <- "target" Spacing id
  
  Expression <- id / Literal

  Port <- id "->" id

  Reactor  <- "reactor" _ Header _ Body

  Composite  <- "comoposite" _ Header _ Body

  Constructor  <- "constructor" _ EmbeddedStatement

  Clock  <- "clock" _ Header _ 

  Header <- id _ Args / id
  
  Args <- "(" _ Param* _ ")"
  
  InOutParamTrig <- Input / Output / Parameter / Trigger

  Input <- 'input' _ Param

  Output <- 'output' _ Param

  Parameter <- 'parameter' _ Param

  Trigger <- 'trigger' _ Param

  Param <- id ((":" Type _ "(" Expression ")") / (":" Type) )? 

  Type <- id

  Body <- "{" Spacing Stament* "}"

  id <- [a-zA-Z]+ [a-zA-Z.]*
  
  Literal <- NumLiteral / StringLiteral

#  NumLiteral <- [0-9]* "."? [0-9]+ ("f" / "d")? 
  NumLiteral <- [0-9]* 

  StringLiteral <- "'" [^\'\"]+ "'" /  "\"" [^\"]+ "\"" #this is perhaps too simple, but for now

  Reaction <- "reaction" Args (_ "->" _ ( Args / id ) )? Spacing EmbeddedStatement

  Spacing  <- ([\s] / Comment)*

  Comment  <- '//' (!EndOfLine .)* EndOfLine

  EndOfLine  <- '\r\n' / '\n' / '\r'

  EndOfFile  <- !.

  _ <- [\s]*

  __ <- [\s]+
