name: Lingua Franca tests

on:
  workflow_call:
    # FIXME: remove these
    inputs:
      compiler-ref:
        required: false
        type: string
      runtime-ref:
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PNPM_HOME: /home/runner/.local/share/pnpm
    steps:
      - name: Check out reactor-ts repository
        uses: actions/checkout@v3
      - name: Read lingua-franca-ref.txt
        id: lf
        run: echo "ref=$(cat lingua-franca-ref.txt)" >> $GITHUB_OUTPUT
      - name: Check out lingua-franca repository
        uses: actions/checkout@v3
        with:
          repository: lf-lang/lingua-franca
          path: ./lingua-franca
          ref: ${{ steps.lf.outputs.ref }}
          fetch-depth: 0
      - name: Prepare build environment
        uses: ./lingua-franca/.github/actions/prepare-build-env
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install reactor-ts globally
        run: |
          echo "${PNPM_PATH}" >> $GITHUB_PATH
          pnpm install -g ./reactor-ts
      - name: Perform Lingua Franca TypeScript tests
        working-directory: lingua-franca
        run: |
          ./gradlew test --tests org.lflang.tests.runtime.TypeScriptTest.*
